### ISSUE TITLE
Find Venue/Date for 2018 Edition

### ISSUE THREAD

**Issue by href** [SwissPy/sps18#1]
This task is completed once the date/venue has been published on the website.

**Comment by ccdesales** [comment]
@sfkeller would the HSR be a venue option for SPS 2018? This is assuming the conference takes place once again on February. 

I'm asking to know if we still have that option, as I heard they were doing construction work to the Aula.

**Comment by sfkeller** [comment]
I'll ask: Fr. 16. Februar 2018? ca. 150 - 200 persons?

**Comment by ccdesales** [comment]
Yes, its sounds more or less like that.

**Comment by sfkeller** [comment]
I checked with the administration and they just confirmed, that the Aula is available at Fr. 16. February 2018. Someone should a.s.a.p. book it as provisional reservation: Should I?

**Comment by href** [comment]
We talked about putting out a call for venues to see other options after the general assembly.

Personally I'm open to other venues, but if we want this done somewhere else we need someone to seriously champion that venue the way that @sfkeller and @dbrgn are in the case of HSR.

So until we have a clear alternative, I think you should create that provisional reservation.

**Comment by sfkeller** [comment]
Done :-) I  have now sent a provisional reservation to our admin desk for the Aula at Fr. 16. February 2018.

**Comment by href** [comment]
@sfkeller Can you put a definite reservation on the Aula on February 16th? I think we're ready to make this official.

**Comment by sfkeller** [comment]
Done.
