### ISSUE TITLE
Order Merchandise: Lanyards, T-Shirts

### ISSUE THREAD

**Issue by href** [SwissPy/sps18#4]
Last time we were way too late to order these things and it got more expensive and more rushed than it should have been.

This time we want to order the lanyards from China. We can basically order 250 lanyards for a fraction of the price we paid last time.

Same goes for the t-shirts. I personally would go for https://www.textil-grosshandel.eu again. They did a great job last time. However this is up to the person taking over this task. The mistake I made last year is to wait for the sizes of everyone before placing the order. Instead we can just get a bunch of t-shirts for various sizes early.

This year we should have separate helper and speaker t-shirts (color). This would make it much easier to identify speakers.

**Comment by The-Compiler** [comment]
How many shirts from 2017 are still left? IIRC, those were deliberately without a date, so we could re-use whatever is over?

**Comment by dbrgn** [comment]
Yep that would probably be good. We still have quite a few left.

**Comment by href** [comment]
The only thing that sucks about the old shirts is the fact that we might get some of the same helpers as last time and they would then get the same shirt again. Not that that's a big deal.

**Comment by dbrgn** [comment]
No. And if they already have a shirt they could even bring it along (I don't need a third Python Summit shirt) :)

**Comment by href** [comment]
In this case let's have a count of the existing shirts so we now how much we need to supplement. Also we'd still need new colours for the speakers.

**Comment by href** [comment]
Existing t-shirt count:

- 2x XXXL
- 3x XXL
- 13x XL
- 9x L
- 2x M
- 2x S

**Comment by href** [comment]
Anyone want to take on the ordering of t-shirts and lanyards? We have the money and there's nothing stopping us from going ahead here. The later we do this the more expensive and stressful it is going to be.

The recipient of the merchandise would probably be @dbrgn as we are located at HSR again.

**Comment by dbrgn** [comment]
This offer for lanyards looks pretty nice:

https://de.aliexpress.com/item/300pcs-lot-2-5-90cm-custom-lanyards-custom-bule-lanyard-heat-transfer-logo-printing-lanyard-OEM/32651563308.html

210$ for 250 custom-printed lanyards including UPS shipping. (At that price, there would be about 36 CHF additionally for VAT and fees.)

**Comment by pandastrail** [comment]
I'll take this issue and take on the ordering of the T-Shirts. Will double check with http://www.socialfabric.ch first, and see if they can match the price. I can also order the lanyards too. If you concur, @href can delete the "open position" label on this one and assign it to me. Or is there a way for me to pull it? Cheers!

**Comment by dbrgn** [comment]
@pandastrail I added you to the association team and assigned you! :)

Don't forget that we already have quite a few shirts left over from last time!

**Comment by href** [comment]
Awesome @pandastrail. Thanks for taking over!

**Comment by pandastrail** [comment]
No problem, I apologize for being sooo quiet, haha. I kind of was minimized by a project at work, but I'm done with that... Cheers!

**Comment by dbrgn** [comment]
@pandastrail did you already find a supplier for customized lanyards?

**Comment by pandastrail** [comment]
@dbrgn How many do we need? Do we have leftovers? I have looked a couple of suppliers at aliexpress.com but have not yet ask for an offer or something similar. Can you point me to the custom design/color that we want?

**Comment by pandastrail** [comment]
This [one](https://www.schluesselbaender.de/inspirationen/oeko-schluesselbaender/) looks quite cool. Or maybe this [one](http://oeko-werbeartikel.eu/08/lanyard-aus-recycelten-pet-fasern/)?

**Comment by pandastrail** [comment]
On another topic, Social Fabric has not yet sent an offer, so I will move on with another supplier. Can someone point me to the logo/design? And, I believe there were black last year, right? So, same color for this edition?

**Comment by href** [comment]
In this case I'd just go with https://www.textil-grosshandel.eu again, like last year. I had a good experience with them.

This is what we ordered:
![screenshot of mail 08-11-17 09-27-01](https://user-images.githubusercontent.com/273163/32538654-fe855d8c-c466-11e7-8e65-82095b6e65fa.png)

This is the design that was used (logo white, background transparent):
[summit-ohne-hintergrund-v2.pdf](https://github.com/SwissPy/sps18/files/1453071/summit-ohne-hintergrund-v2.pdf)

I think the color can also be different than black. I would go for a dark one though, if only because the logo has already been prepared for that kind of print. It's somewhat of a bike-shedding question, so maybe you decide @pandastrail :)

As for the lanyards, the second link looks good to me. Do you need help designing the custom print for it? Or do you want to do it yourself? I can provide you with all the design materials we have so far (logos, fonts).

**Comment by pandastrail** [comment]
@href Please send me what you have regarding the custom print for the lanyards... and I will go from there.

On the logo for the shirts, did they worked with the 'summit-ohne-hintergrund-v2.pdf' as it is? Or do we a separate file with the image?

**Comment by href** [comment]
They worked directly with that. They will send you a an example to confirm the expected result.

I'll post the files tomorrow.

**Comment by href** [comment]
Here you go @pandastrail:
[Archive.zip](https://github.com/SwissPy/sps18/files/1464699/Archive.zip)

The files are in SVG (with text converted to outline) and in the original [Sketch](https://www.sketchapp.com) format. The font we use is [Open Sans](https://fonts.google.com/specimen/Open+Sans).

Note that you also need to order DIN A6 transparent sleeves (Ausweishüllen) together with the Lanyards (there's usually a combination deal). We'll print the tickets ourselves through HSR and put them into the sleeves.

Something like this:
![screenshot of safari 12-11-17 14-40-49](https://user-images.githubusercontent.com/273163/32699525-7ecc0b6e-c7b7-11e7-93db-2247b1811e22.png)

Let me know if you need anything else.

**Comment by dbrgn** [comment]
@pandastrail I forgot to put the shirt count here too, only posted it to Slack.

This is how many shirts we still have from last time:

2x XXXL
3x XXL
13x XL
9x L
2x M
2x S

31 in total.

**Comment by pandastrail** [comment]
Just to double check and make sure I order the right thing, are the badges in a vertical or horizontal orientation? I think usually size A6 will be 148 mm tall x 105 mm wide (vertical), just like the photo of the badges you posted @href

**Comment by dbrgn** [comment]
IIRC they were vertical last time (taller than wide).

**Comment by href** [comment]
> A6 will be 148 mm tall x 105 mm wide (vertical)

This is correct!

**Comment by pandastrail** [comment]
Thanks! @href Do you happen to have the logo for the T-Shirt with a background, or without a transparent background? Or maybe in another format as the .pdf?

**Comment by href** [comment]
I can create one - what is it for? What color do you need? Formats I can create are PDF and SVG.

**Comment by pandastrail** [comment]
It is for another quote, but wait, I think I can find a solution with I have. I'll let you know if I need something. Thanks!

**Comment by pandastrail** [comment]
On the badge sleeves, I'm trying to get everything at one place. However, the max. size that they have is 103 x 134 mm, i.e. the  A6 size (105 × 148 millimeters) is too big for it! I'm having trouble to find an A6 sleeve somewhere...

Would it be possible to scale the badge down to an A7  (74 × 105 mm)?

**Comment by href** [comment]
I think that's doable

**Comment by pandastrail** [comment]
Nevermind, I think I just found something...

**Comment by dbrgn** [comment]
Yeah, I think A7 is perfectly fine (maybe even a bit less bulky).

**Comment by pandastrail** [comment]
Great, cost are much greater for an A6, because I may need to order them here in CH oder in D. So, I will go for the A7. Thx!

**Comment by pandastrail** [comment]
Polo shirts, lanyards and sleeves delivered!

**Comment by dbrgn** [comment]
That was fast!

**Comment by href** [comment]
Just to confirm @pandastrail , you've gotten A7 right? Not that I get the wrong size printed :)

**Comment by pandastrail** [comment]
Yeah, the sleeve is 82 cm wide x 104 cm tall , was the closest to an A7.

**Comment by href** [comment]
> 82 **cm** wide x 104 **cm** tall

That is humongous ;)

Would an A7 fit? With 105mm it would slightly overlap at the top. The printing is done by @sfkeller's team at HSR and it would probably be best if they could just cut A7, without having to shave off the extra 1mm.

**Comment by href** [comment]
Also, can you make it to the venue before 07:45 with lanyards and t-shirts, @pandastrail? A lot hangs on this ;)
