### ISSUE TITLE
Post and Promote a Call for Proposals

### ISSUE THREAD

**Issue by href** [SwissPy/sps18#5]
This task would greatly benefit from someone volunteering to be the point of contact for all speakers. Obviously we a venue and date first (#1).

**Comment by sfkeller** [comment]
Some more outreach needed? Just found this http://techup.ch/2369/swiss-python-summit-2017 .

**Comment by href** [comment]
Thanks @sfkeller for pointing that out. Done: http://techup.ch/2554/swiss-python-summit-2018

**Comment by sfkeller** [comment]
Do we have now enough proposals? I'm aware of a master student who is willing to submit one in sort notice. And just now I realized, that I could have submitted a very cool proposal about GeoPySpark...

**Comment by dbrgn** [comment]
@sfkeller we didn't take the link offline yet, so if you're quick you can still submit :)

**Comment by Styp** [comment]
Nice! @sfkeller made my day...
