### ISSUE TITLE
Hands on area

### ISSUE THREAD

**Issue by loleg** [SwissPy/sps18#9]
@davidhalter and I have been bouncing some ideas around during the [DINAcon Hacknight](https://dinacon.ch/en/agenda/hacknight/) last weekend, similar to [PyCon.DE dev sprints](https://de.pycon.org/schedule/sprint/), [ZuriHac projects](https://zurihac.info/#projects), and other hackathons. We thought it would be a good idea to pitch something like this for SwissPy next year. This could be a workshop, side event, or evening activity.

**Comment by betatim** [comment]
I'd be interested in sprints the day after the conference.

* Could we get a room the day after (in which you can eat and drink)?
* Is there somewhere to get food during the day nearby?

**Comment by sfkeller** [comment]
Yes (see e.g. ZuriHac) and yes.

**Comment by ccdesales** [comment]
AFAIK this kind of companion events normally happens when there are no ongoing talks, so it would be pretty much like last year's Django Girls workshop, either before or after the main track. 

If there's availability of space and somebody wants to take responsibility to organise I don't see a reason against it.

**Comment by betatim** [comment]
Maybe @sfkeller can give us a feeling on how much work/responsibility it would be to be the person "in charge"?

I am away the days before the SPS so hesitant to take on too much responsibilities/orga work as I won't be able to do it justice. However I would enjoy a sprint on Saturday.

I would suggest:
* announce ~now there will be sprints after the conference so people can schedule it
* google form to collect who will sprint on what.
* short annoucenment during the conference to say that sprints are happening and which projects will be there/what people will be sprinting on (based on the google form)
* someone with a key/responsible to turn up around 9am on Saturday
* help people organise themselves into small groups according to what they want to sprint on
* order pizza and drinks at lunch, collect money from people to pay for pizza
* make sure everyone is out at 5pm

WDYT?

**Comment by sfkeller** [comment]
Difficult to say out of my head. Have to look it up....

**Comment by loleg** [comment]
Thanks very much for considering the idea. As it turned out, the [Open Food Hackdays](https://food.opendata.ch/#hackdays) are taking place on the same date as the Summit. And due to a shortage of help, I have to be in Basel to support them. But I will be there spreading Python love and [bootstraps](https://github.com/DrkSephy/django-hackathon-starter) & [cookiecutters](https://github.com/audreyr/cookiecutter#python), encouraging people to tweet questions at your hashtag and follow the SwissPy action remotely. Closing this until next year & wishing you all an awesome event!
